### ISSUE TITLE
Cannot create DefaultDynamo with default constructor

### ISSUE THREAD

**Issue by pinaf** [yegor256/s3auth#260] opened 2015-01-19 23:31 UTC
Calling `new DefaultDynamo()` results in an error because of a lack of Manifest properties expected by the constructor.
```
java.lang.IllegalArgumentException: Attribute 'S3Auth-AwsDynamoTable' not found in MANIFEST.MF file(s) among 66 other attribute(s): ["Agent-Class", "Ant-Version", "Archiver-Version", "Bnd-LastModified", "Build-Id", "Build-Jdk", "Build-Timestamp", "Built-By", "Built-Date", "Bundle-Activator", "Bundle-Category", "Bundle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Can-Redefine-Classes", "Class-Path", "Created-By", "Export-Package", "Extension-Name", "Fragment-Host", "Ignore-Package", "Implementation-Build", "Implementation-Build-Date", "Implementation-Title", "Implementation-URL", "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version", "Implementation-Version-Detail", "Import-Package", "Include-Resource", "JCabi-Build", "JCabi-Date", "JCabi-Version", "Java-Vendor", "Java-Version", "Lombok-Version", "Main-Class", "Manifest-Version", "Originally-Created-By", "Os-Arch", "Os-Name", "Os-Version", "Package", "Premain-Class", "ReXSL-Build", "ReXSL-Date", "ReXSL-Version", "Require-Capability", "Scm-Connection", "Scm-Revision", "Scm-Url", "Specification-Title", "Specification-Vendor", "Specification-Version", "Time-Zone-Database-Version", "Tool", "X-Compile-Source-JDK", "X-Compile-Target-JDK", "url"]
	at com.jcabi.manifests.Manifests.read(Manifests.java:274)
	at com.s3auth.hosts.DefaultDynamo.<init>(DefaultDynamo.java:121)
```

Test code for `DefaultDynamoTest`
```
    /**
     * DefaultDynamo can instantiate from default constructor.
     * @throws Exception If there is some problem inside
     */
    @Test
    public void instantiatesDefault() throws Exception {
        MatcherAssert.assertThat(
            new DefaultDynamo(),
            Matchers.not(Matchers.nullValue())
        );
    }
```

**Comment by davvd** [comment] 2015-01-20 09:58
we'll find someone to do this task, soon

**Comment by davvd** [comment] 2015-01-20 10:01
@jenya could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment] 2015-01-20 10:02
@pinaf thanks for reporting! I topped your account for 15 mins, transaction AP-6TE365103J804431S

**Comment by pinaf** [comment] 2015-01-20 15:36
@davvd thank you

**Comment by davvd** [comment] 2015-01-21 13:33
@dpisarenko please go ahead with this task, it's yours

**Comment by dpisarenko** [comment] 2015-01-21 20:19
@pinaf What should happen, if no `S3Auth-AwsDynamoTable` is specified in the manifest?

  1. The creation of `DefaultDynamo` should fail as now.
  1. The constructor of DefaultDynamo should use a default value instead.
  1. Something else.

If the answer is 2 (default value), which default value for `S3Auth-AwsDynamoTable` should I use?

**Comment by dpisarenko** [comment] 2015-01-21 20:24
FYI: I tried to fix the error by adding `S3Auth-AwsDynamoTable: XXX` to files

  1. s3auth-relay/src/main/resources/META-INF/MANIFEST.MF
  1. s3auth-relay/src/test/resources/META-INF/MANIFEST.MF
  1. s3auth-rest/src/test/resources/META-INF/MANIFEST.MF

but it didn't help.

Another option is to set the value explicitly (by appending a Manifest value) before creating the `DefaultDynamo` instance, but I suppose this is not what we should do.

**Comment by dpisarenko** [comment] 2015-01-21 20:29
@davvd Please find someone to review my PR https://github.com/yegor256/s3auth/pull/263 .

**Comment by pinaf** [comment] 2015-01-21 23:34
@dpisarenko since `DefaultDynamo` lies in s3auth-hosts, you have to add it to the MANIFEST.MF in that folder. You also need to add the other manifest properties that are used in the constructor (they are 4 in total). As for the values, I suppose you can use the same ones in the s3auth-rest manifest:
```
S3Auth-AwsDynamoKey: ${dynamo.key}
S3Auth-AwsDynamoSecret: ${dynamo.secret}
S3Auth-AwsDynamoTable: ${dynamo.table}
S3Auth-AwsDynamoEntryPoint: http://localhost:${dynamodb.port}
```

**Comment by pinaf** [comment] 2015-01-21 23:36
@dpisarenko Also, I would leave it failing if it can't find the properties (option 1)

**Comment by dpisarenko** [comment] 2015-01-23 13:51
@pinaf The PR with the bugfix has been merged. Please look at it and if everything is OK, close this issue. Thanks!

**Comment by pinaf** [comment] 2015-01-23 15:01
@dpisarenko thank you

**Closed** 2015-01-23 15:01 UTC
Labels: 30 mins, @dpisarenko, bug, DEV

**Comment by davvd** [comment] 2015-01-26 10:33
@dpisarenko thank you, added **30 mins** to your acc, payment num is `50663437`... +30 added to your rating, current score is: [+521](http://www.netbout.com/b/35089?open=rating)
