### ISSUE TITLE
is https supported on s3auth?

### ISSUE THREAD

**Issue by oviwankenobi** [yegor256/s3auth#334] opened 2016-08-29 13:30 UTC
hi, I have setup successfully the http basic auth for a http api; is it possible to set it up for https as well? how? thank you.

prolly linked with this
https://github.com/yegor256/s3auth/issues/271

**Comment by oviwankenobi** [comment] 2016-08-29 13:33
linked with this
[https://github.com/yegor256/s3auth/issues/271](url)

**Comment by davvd** [comment] 2016-09-02 09:59
@yegor256 please do something about this issue

**Comment by jandppw** [comment] 2016-09-14 08:16
Yes please.

A first idea is to put a CloudFront in front of your server, using certificates from Amazon itself, at no additional cost. You could do this with terraform quickly (willing to help).
Yet, the communication between the CloudFront distribution and your server would still be over http, and thus insecure.

A better solution would be to enable https on your server. You can do this with a free certificate from https://letsencrypt.org. That does required some (supported) configuration of the server (which is out of my comfort zone).

**Comment by greggmojica** [comment] 2016-09-17 03:00
+1

**Comment by yegor256** [comment] 2016-11-21 21:15
@oviwankenobi this is definitely a duplicate of #271, but thanks for submitting. @jandppw thanks for your suggestion, we will take a look at it soon.

**Closed** 2016-11-24 07:38 UTC
