### ISSUE TITLE
Impossible to mock of static methods in final classes

### ISSUE THREAD

**Issue by darkled** [yegor256/s3auth#254] opened 2015-01-13 14:06 UTC
I need to mock `com.s3auth.relay.LocalHost.isIt(String)` method but it is impossible due to the following reasons:
- mockito is not able to mock final classes
- powermock is not able to do it as well because of the [defect in powermock](https://code.google.com/p/powermock/issues/detail?id=531) due to change in junit 4.12

Since we have many final classes this functionality should be available.

**Comment by yegor256** [comment] 2015-01-13 14:25
@darkled what do you suggest?

**Comment by darkled** [comment] 2015-01-13 14:30
@yegor256 The defect of powermock seems to be fixed now, so we can check whether this fix is delivered within the newest version of powermock. If yes than we use newest powemock version and if not we can try to rollback to any of older versions of junit / powermock.

**Comment by yegor256** [comment] 2015-01-13 14:36
@darkled I'm strongly against powermock. It's a very dangerous tool and should be used only when a third-party library has to be mocked. It's not our case. If some of our classes are not mockable - it's our bug and should be fixed. The class has to be re-designed. Powermock is not a solution.

**Comment by darkled** [comment] 2015-01-13 14:44
@yegor256 in this case `LocalHost` needs to be re-designed as a non-final class

**Comment by yegor256** [comment] 2015-01-13 14:51
@darkled I don't think so. Take a look: http://www.yegor256.com/2014/11/20/seven-virtues-of-good-object.html#5.-his-class-doesn't-have-anything-static

I think the problem is that there is a static method. Some refactoring is probably required, that will remove that. Explain what do you need to be done, so that you can proceed with your task. But keep in mind that all classes should be final and static methods are evil :)

**Comment by darkled** [comment] 2015-01-13 19:35
@yegor256 I think I am a bit confusing now but nevertheless will try to explain now what I wanted to have with mocked `LocalHost`. The main idea was to provide functionality similar to this:
```java
public static boolean isIt(@NotNull final String name) {
    return "relay.s3auth.com".equals(name) || name.startsWith("localhost");
}
```
But such changes in sources lead to few broken tests what I would prefer to avoid since I am not sure about the idea of introducing such method and javadoc looks quite confusing (it looks like it is a point for another issue).

So, this method can be re-designed to be non-static and `LocalHost` can hold a new field `name` in order to avoid using of powermock. 

By the way, a small off-topic, may I ask why do you not like powermock? Could you remember any example when it is a really terrible decision?

**Comment by yegor256** [comment] 2015-01-13 20:09
@darkled I would suggest to start with a new issue, about that confusing documentation you mentioned. When documentation is fixed, you review the situation again and find a solution much faster.

Powermock usage will ruin the project faster than singletons and global variables. Mocking in general is a bad practice (see http://www.yegor256.com/2014/09/23/built-in-fake-objects.html), but powermock turns it to extreme. In short, powermock encourages tests to know too much about object internals. This leads to tight coupling between tests and objects. In the end, neither tests nor objects are maintainable.

**Comment by darkled** [comment] 2015-01-14 14:11
@yegor256 created #257. Your point about mocking is clear now, thanks.

**Closed** 2015-09-30 08:47 UTC
