### ISSUE TITLE
build failure while trying to run the project locally

### ISSUE THREAD

**Issue by simonjenga** [yegor256/s3auth#311] opened 2015-10-19 05:44 UTC
Executing`mvn clean install -Phit-refresh -Dport=8080` leads to the following error:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[?[0;37mINFO?[m] com.s3auth.hosts.DefaultDynamo: #load(): {} in 2.07s
[?[2;37mDEBUG?[m] com.s3auth.hosts.DefaultDynamo: #load(): {} cached in 2s, valid for 5min
[?[2;37mDEBUG?[m] com.s3auth.hosts.Domains: #iterator(): java.util.concurrent.ConcurrentHashMap$ValueIterator@806ddf in 49.66-Ás
[?[2;37mDEBUG?[m] com.s3auth.hosts.DynamoHosts$Wrap: #iterator(): java.util.concurrent.ConcurrentHashMap$ValueIterator@806ddf in 828.82-Ás
[?[2;37mDEBUG?[m] com.s3auth.hosts.DynamoHosts: #domains(com.s3auth.rest.RqUser$1@2ae6eb): [] in 2.28s
[?[2;37mDEBUG?[m] com.s3auth.hosts.Domains: #iterator(): java.util.concurrent.ConcurrentHashMap$ValueIterator@89bbff in 11.93-Ás
[?[2;37mDEBUG?[m] com.s3auth.hosts.DynamoHosts$Wrap: #iterator(): java.util.concurrent.ConcurrentHashMap$ValueIterator@89bbff in 463.49-Ás
[?[2;37mDEBUG?[m] com.s3auth.hosts.SyslogHosts: #domains(com.s3auth.rest.RqUser$1@2ae6eb): [] in 2.30s
[?[2;37mDEBUG?[m] com.s3auth.hosts.Domains: #iterator(): java.util.concurrent.ConcurrentHashMap$ValueIterator@65ff33 in 15.78-Ás
[?[2;37mDEBUG?[m] com.s3auth.hosts.DynamoHosts$Wrap: #iterator(): java.util.concurrent.ConcurrentHashMap$ValueIterator@65ff33 in 1.24ms
Running com.s3auth.rest.TkAppITCase
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.264 sec - in com.s3auth.rest.TkAppITCase

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- exec-maven-plugin:1.3.2:exec (casperjs-test) @ s3auth-rest ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................ SUCCESS [11.473s]
[INFO] s3auth-hosts ...................................... SUCCESS [1:27.912s]
[INFO] s3auth-relay ...................................... SUCCESS [1:19.146s]
[INFO] s3auth-rest ....................................... FAILURE [47.577s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "hit-refresh" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (casperjs-test) on project s3auth-rest: Command execution failed. Process exited with an error: -2146232576 (Exit value: -2146232576) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :s3auth-rest
[INFO] #stop(56016): in 1ms
```

**Comment by davvd** [comment] 2015-10-22 14:14
@yegor256 dispatch this issue please, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment] 2018-03-27 10:18
@simonjenga seems to be a duplicate of #338

**Comment by 0crat** [comment] 2018-03-27 10:19
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Closed by yegor256** 2018-03-27 10:18 UTC

**Comment by 0crat** [comment] 2018-03-27 10:34
The job is not in WBS, won't close the order

**Comment by 0crat** [comment] 2018-03-27 11:35
The job is not in WBS, won't close the order
