### ISSUE TITLE
java.lang.IllegalStateException: thread 'back-69' in group 'back' interrupted

### ISSUE THREAD

**Issue by lukesaunders** [yegor256/s3auth#348] opened 2017-03-23 18:21 UTC
When hosting a site on s3 behind the hosted s3auth, we often get this 500 error at random when loading an HTML page or static asset: https://gist.github.com/lukesaunders/a04e0de7eeabe1bd13417f3ce9ccecbb

It happens only when hosting a page with many assets and hence triggers many requests simultaneously, so it seems to be some kind of throttling. 

What to do?

**Comment by nikita-leonov** [comment] 2017-05-10 23:41
Have you found a solution? I am experiencing the same — https://gist.github.com/nikita-leonov/87eac248a3a2de13da76402757a1e030

**Comment by yegor256** [comment] 2017-05-11 05:37
@lukesaunders @nikita-leonov I set the delay to 2 minutes, instead of 30 seconds, in 8eb99e2 Let me try to deploy and we'll see

**Comment by yegor256** [comment] 2017-05-11 05:37
@rultor deploy

**Comment by yegor256** [comment] 2017-05-11 08:18
@rultor deploy

**Comment by yegor256** [comment] 2017-05-11 08:38
@rultor deploy

**Comment by yegor256** [comment] 2017-05-11 08:52
@rultor deploy

**Comment by yegor256** [comment] 2017-05-11 09:14
@lukesaunders @nikita-leonov try it out now... Should be better, I guess

**Comment by nikita-leonov** [comment] 2017-05-11 09:19
Looks like it is still happening with the same regularity. 500 status code and the exception with `java.lang.IllegalStateException: thread 'back-90' in group 'back' interrupted`. Is there any additional information that I can provide you to simplify investigation of this issue?

**Comment by nikita-leonov** [comment] 2017-05-11 09:25
I assume it is actually happening because of rate limits — http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html Content heavy static websites may have many links to various styles, JavaScripts, images etc. As result, multiple loads of the same website can be way above hundreds of requests, as result 500 returned. This is still an assumption that needs to be validated.

**Comment by russelldc** [comment] 2017-08-11 20:16
Still seeing this error today.

**Comment by yegor256** [comment] 2018-03-27 10:12
@lukesaunders @russelldc @nikita-leonov @jart I'm sorry this bug is still not fixed. We didn't have enough funds/time to work on the project. However, recently we received some donations from our grateful users and will continue to fix issues and introduce new features. Would be great if you can also donate -- to help us move forward faster. Here is the link: https://www.0crat.com/contrib/C3RP1J1CH

**Comment by 0crat** [comment] 2018-03-27 10:33
Job [#348](https://github.com/yegor256/s3auth/issues/348) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-03-27 10:34
Thanks for your contribution, @lukesaunders[/z](https://www.0crat.com/u/lukesaunders)! If you would be a member of [the project](https://www.0crat.com/p/C3RP1J1CH), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2018-03-27 10:41
The job [#348](https://github.com/yegor256/s3auth/issues/348) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C3RP1J1CH/861067104); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by llorllale** [comment] 2018-03-28 16:39
@yegor256 Why is `SmartHost.fetch` timed to 5 seconds? 

It is being decorated by `FastHost` according to stacktraces [1](https://gist.github.com/nikita-leonov/87eac248a3a2de13da76402757a1e030) and [2](https://gist.github.com/lukesaunders/a04e0de7eeabe1bd13417f3ce9ccecbb).

Seems like `FastHost` is concerned with times, not `SmartHost`.

**Comment by 0crat** [comment] 2018-04-01 13:11
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment] 2018-04-03 14:37
@0crat waiting for review on PR #369

**Comment by 0crat** [comment] 2018-04-03 14:48
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RP1J1CH](https://www.0crat.com/p/C3RP1J1CH), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="931479052">
   <created>2018-04-03T14:48:44.449Z</created>
   <type>Register impediment</type>
   <token>github;yegor256/s3auth;348;378272835</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/s3auth#348</param>
      <param name="repo">yegor256/s3auth</param>
      <param name="issue">348</param>
      <param name="comment">378272835</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment] 2018-04-03 14:48
> @0crat waiting for review on PR #369  ([here](https://github.com/yegor256/s3auth/issues/348#issuecomment-378272835))

@llorllale The impediment for [#348](https://github.com/yegor256/s3auth/issues/348) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment] 2018-04-03 14:48
> @0crat waiting for review on PR #369  ([here](https://github.com/yegor256/s3auth/issues/348#issuecomment-378272835))

@llorllale Job [#348](https://github.com/yegor256/s3auth/issues/348) is already on hold

**Comment by llorllale** [comment] 2018-04-13 14:08
@yegor256 now that PR #369 has been merged, do we need to perform a release in order to test?

**Comment by llorllale** [comment] 2018-04-14 14:46
@yegor256 nevermind

**Comment by llorllale** [comment] 2018-04-14 14:48
@lukesaunders @nikita-leonov @russelldc can you guys please check to see if we can close this issue now that PR #369 was merged?

**Comment by yegor256** [comment] 2018-04-18 13:11
@llorllale we need to re-deploy in order to see the changes onine

**Comment by llorllale** [comment] 2018-04-18 13:13
@yegor256 oh I see. Please let us know then

**Comment by yegor256** [comment] 2018-04-19 14:33
@rultor deploy

**Comment by yegor256** [comment] 2018-04-19 14:58
@rultor deploy

**Comment by yegor256** [comment] 2018-04-19 15:32
@llorllale deployed

**Comment by llorllale** [comment] 2018-04-19 15:33
@yegor256 thanks!

**Comment by llorllale** [comment] 2018-04-19 15:33
@lukesaunders @nikita-leonov @russelldc can you guys please check to see if we can close this issue now that PR #369 was merged?

**Comment by llorllale** [comment] 2018-04-23 12:50
@lukesaunders @nikita-leonov @russelldc ping

**Comment by russelldc** [comment] 2018-05-01 17:55
@llorllale I was able to successfully load our page a few times, but I'm not sure how to verify it never happens.

**Comment by llorllale** [comment] 2018-05-05 20:36
@russelldc how were you reproducing the error when you said you were experiencing it [here](https://github.com/yegor256/s3auth/issues/348#issuecomment-321908754)?

**Comment by llorllale** [comment] 2018-05-05 20:37
@nikita-leonov ping

**Comment by llorllale** [comment] 2018-05-08 17:41
@russelldc thank you

**Comment by llorllale** [comment] 2018-05-08 17:44
@yegor256 can we close this?

Of the 3 reporters of this issue:
* 1 is no longer in a position to verify the fix
* 1 is not experiencing the error, but is not sure how to reproduce
* 1 is unresponsive

**Comment by yegor256** [comment] 2018-05-10 12:56
@llorllale OK, closing. If we have a similar problem in the future, let's report a new ticket

**Closed by yegor256** 2018-05-10 12:56 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-05-10 13:12
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @llorllale[/z](https://www.0crat.com/u/llorllale), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-05-10 13:12
The job [#348](https://github.com/yegor256/s3auth/issues/348) is now out of scope

**Comment by ypshenychka** [comment] 2018-05-10 19:58
@nikita-leonov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your messages ([here](https://github.com/yegor256/s3auth/issues/348#issuecomment-300642451), [here](https://github.com/yegor256/s3auth/issues/348#issuecomment-300733104) and [here](https://github.com/yegor256/s3auth/issues/348#issuecomment-300734502)) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment] 2018-05-10 19:59
@russelldc According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/s3auth/issues/348#issuecomment-321908754) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment] 2018-05-14 19:26
@nikita-leonov @russelldc Please consider my remarks above.

**Comment by 0crat** [comment] 2018-05-16 14:28
Order was finished, quality is "acceptable": +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment] 2018-05-16 14:28
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
