### ISSUE TITLE
Could it be possible for s3auth to serve over https?

### ISSUE THREAD

**Issue by rygo6** [yegor256/s3auth#271] opened 2015-02-25 22:50 UTC
I am wanting to set up something to install iOS apps from an s3auth'ed bucket. The peculiar thing about installing iOS apps from web is that iOS requires it to be served from an https url. I am curious to know, is there someway to get s3auth to respond to https?

**Comment by yegor256** [comment] 2015-02-26 01:55
@rygo6 we had a ticket about it (https://github.com/yegor256/s3auth/issues/8), but I'm not sure where we are in this feature. I'll check soon and report here

**Comment by rygo6** [comment] 2015-03-08 03:32
@yegor256 Looking at the ticket it appears like this functionality has been merged into s3auth. Is that correct? Is there documentation on how to use it?

**Comment by yegor256** [comment] 2015-03-09 06:08
@rygo6 yes we implemented all this, but I can't remember whether it works or not. let's try to assign this problem to @carlosmiranda since he was in charge of this issue

**Comment by davvd** [comment] 2015-03-09 10:12
I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment] 2015-03-09 10:14
@carlosmiranda it's yours, budget is 30 mins, please go ahead

**Comment by carlosmiranda** [comment] 2015-03-09 11:31
@davvd Assign someone else please.

**Comment by carlosmiranda** [comment] 2015-03-09 11:31
@yegor256 @rygo6 Sorry guys, got my hands full on various things the past few days... no time to attend to this. :(

**Comment by davvd** [comment] 2015-03-09 13:10
> @davvd Assign someone else please.

@carlosmiranda OK, I will try to assign someone else

**Comment by davvd** [comment] 2015-04-17 09:50
@rygo6 I set milestone here to `1.0`, let me know if it is wrong

**Comment by oviwankenobi** [comment] 2016-08-29 13:33
was there any progress made on this matter? (https support)
thank you

**Comment by yegor256** [comment] 2018-03-27 10:26
@rygo6 duplicate of #305

**Comment by yegor256** [comment] 2018-03-27 10:26
@rygo6 @oviwankenobi @jart I'm sorry this bug is still not fixed. We didn't have enough funds/time to work on the project. However, recently we received some donations from our grateful users and will continue to fix issues and introduce new features. Would be great if you can also donate -- to help us move forward faster. Here is the link: https://www.0crat.com/contrib/C3RP1J1CH

**Closed by yegor256** 2018-03-27 10:26 UTC
Labels: 30 mins, DEV, bug

**Comment by 0crat** [comment] 2018-03-27 10:41
The job is not in WBS, won't close the order
