### ISSUE TITLE
Local build fails

### ISSUE THREAD

**Issue by asaen** [yegor256/s3auth#306] opened 2015-09-30 08:39 UTC
Running `mvn clean install -X` under windows 7 leads to the following error:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jcabi:jcabi-ssl-maven-plugin:0.11:keygen (default) on project s3auth: Execution default of goal com.jcabi:jcabi-ssl-maven-plugin:0.11:keygen failed: Can't find resource for bundle sun.security.util.Resources, key yes
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.jcabi:jcabi-ssl-maven-plugin:0.11:keygen failed: Can't find resource for bundle sun.security.util.Resources, key yes
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.util.MissingResourceException: Can't find resource for bundle sun.security.util.Resources, key yes
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at com.jcabi.ssl.maven.plugin.Keytool.createLocaleDependentYes(Keytool.java:178)
        at com.jcabi.ssl.maven.plugin.Keytool.genkey_aroundBody2(Keytool.java:125)
        at com.jcabi.ssl.maven.plugin.Keytool$AjcClosure3.run(Keytool.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
        at com.jcabi.ssl.maven.plugin.Keytool.genkey(Keytool.java:105)
        at com.jcabi.ssl.maven.plugin.Keystore.activate_aroundBody2(Keystore.java:121)
        at com.jcabi.ssl.maven.plugin.Keystore$AjcClosure3.run(Keystore.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
        at com.jcabi.ssl.maven.plugin.Keystore.activate(Keystore.java:119)
        at com.jcabi.ssl.maven.plugin.KeygenMojo.execute(KeygenMojo.java:153)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
```

Output of `mvn -v`:

```
$ mvn -v
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-4T19:29:23+02:00)
Maven home: d:\apps\apache-maven-3.2.5\bin\..
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_31\jre
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by yegor256** [comment] 2015-09-30 16:53
@darkled I suspect the problem is with your Locale (Russian, I assume), not Windows

**Comment by davvd** [comment] 2015-10-01 09:43
@darkled I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment] 2015-10-01 09:43
@darkled attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment] 2015-10-01 09:45
@darkled thanks for reporting! I topped your account for 15 mins, transaction 66379333

**Comment by yegor256** [comment] 2018-03-27 10:19
@asaen seems to be a duplicate of #338

**Closed by yegor256** 2018-03-27 10:19 UTC
Labels: 30 mins, DEV, bug

**Comment by 0crat** [comment] 2018-03-27 10:34
The job is not in WBS, won't close the order
