### ISSUE TITLE
Incomplete documentation: How to fix "JSR-303 validator failed to initialize" error

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/s3auth#228] opened 2014-12-25 18:28 UTC
In
1. `README.md` or
2. `src/site/notes.apt.vm`

provide information about
- whether the error below is relevant and
- if it is, how to fix it.

**How to reproduce**
1. `git clone` the s3auth repository.
2. `cd` into `s3auth/s3auth-hosts` directory.
3. Run `mvn test` there.

Expected result: A message about passed and failed tests.
Actual result: Following error message:

```
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration
, because no Bean Validation provider could be found. Add a provider like Hibern
ate Validator (RI) to your classpath. (see http://www.jcabi.com/jcabi-aspects/js
r-303.html)
[INFO] jcabi-aspects 0.7.22/fd7496f started new daemon thread jcabi-loggable for
 watching of @Loggable annotated methods
```

**Comment by davvd** [comment] 2015-01-08 16:18
@cyberone the task is your hands for the last 13 days.. keep in mind that if it's not closed in the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; added -30 to your rating, now it is equal to [-310](http://www.netbout.com/b/35076?open=rating)

**Comment by davvd** [comment] 2015-01-13 14:09
@aoxa please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment] 2015-01-28 13:42
@aoxa you're holding this ticket for 15 days already. If it's not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). added -30 to your rating, now it is equal to -270

**Comment by davvd** [comment] 2015-01-29 15:31
I'm closing it, thanks all

**Comment by davvd** [comment] 2015-01-29 16:37
my bad, should be open

**Comment by davvd** [comment] 2015-02-02 14:56
@aoxa you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is -330

**Comment by davvd** [comment] 2015-04-17 09:50
@dpisarenko I set milestone here to `1.0`, let me know if it is wrong

**Comment by yegor256** [comment] 2018-03-27 10:29
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Closed by yegor256** 2018-03-27 10:29 UTC
Labels: 30 mins, DEV, bug

**Comment by 0crat** [comment] 2018-03-27 10:45
The job is not in WBS, won't close the order
