### ISSUE TITLE
not able to access s3 and getting the Error

### ISSUE THREAD

**Issue by vikasrachakonda** [yegor256/s3auth#366] opened 2017-10-04 17:46 UTC
```
java.lang.IllegalStateException: thread 'back-60' in group 'back' interrupted
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:182)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.s3auth.hosts.DefaultBucket.name(DefaultBucket.java:94)
	at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:228)
	at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.s3auth.hosts.DefaultHost.fetch_aroundBody4(DefaultHost.java:166)
	at com.s3auth.hosts.DefaultHost$AjcClosure5.run(DefaultHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.s3auth.hosts.DefaultHost.fetch(DefaultHost.java:166)
	at com.s3auth.hosts.SmartHost.fetch_aroundBody6(SmartHost.java:107)
	at com.s3auth.hosts.SmartHost$AjcClosure7.run(SmartHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.s3auth.hosts.SmartHost.fetch_aroundBody8(SmartHost.java:104)
	at com.s3auth.hosts.SmartHost$AjcClosure9.run(SmartHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.s3auth.hosts.SmartHost.fetch_aroundBody10(SmartHost.java:104)
	at com.s3auth.hosts.SmartHost$AjcClosure11.run(SmartHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.s3auth.hosts.SmartHost.fetch(SmartHost.java:104)
	at com.s3auth.hosts.FastHost.fetch_aroundBody0(FastHost.java:89)
	at com.s3auth.hosts.FastHost$AjcClosure1.run(FastHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.s3auth.hosts.FastHost.fetch(FastHost.java:89)
	at com.s3auth.hosts.RejectingHost.fetch(RejectingHost.java:108)
	at com.s3auth.relay.SecuredHost.fetch_aroundBody0(SecuredHost.java:105)
	at com.s3auth.relay.SecuredHost$AjcClosure1.run(SecuredHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.s3auth.relay.SecuredHost.fetch_aroundBody2(SecuredHost.java:102)
	at com.s3auth.relay.SecuredHost$AjcClosure3.run(SecuredHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.s3auth.relay.SecuredHost.fetch(SecuredHost.java:102)
	at com.s3auth.relay.HttpThread.resource(HttpThread.java:247)
	at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:169)
	at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:264)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:701)
```

**Comment by 0crat** [comment] 2017-10-04 17:46
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment] 2017-10-04 19:12
@vikasrachakonda this may happen, but very rarely. Did you just try to refresh the page?

**Comment by vikasrachakonda** [comment] 2017-10-04 19:13
Yes, i am getting the error page

**Comment by vikasrachakonda** [comment] 2017-10-04 19:43
<img width="925" alt="screen shot 2017-10-04 at 3 43 06 pm" src="https://user-images.githubusercontent.com/30442846/31196177-c344aa50-a91a-11e7-9cfa-458645a890b3.png">

i am unable to understand these steps

**Comment by vikasrachakonda** [comment] 2017-10-11 20:50
@yegor256 Can you help out , waiting for your reply

**Comment by yegor256** [comment] 2017-10-12 14:25
@vikasrachakonda what exactly is the problem? Do you know what "bucket" is?

**Comment by ifnull** [comment] 2017-11-29 22:38
We are seeing this issue more frequently now. 500 response with a java backtrace. Refreshing usually resolves.

**Comment by yegor256** [comment] 2018-03-27 10:07
@vikasrachakonda @ifnull I'm sorry this bug is still not fixed. We didn't have enough funds/time to work on the project. However, recently we received some donations from our grateful users and will continue to fix issues and introduce new features. Would be great if you can also donate -- to help us move forward faster. Here is the link: https://www.0crat.com/contrib/C3RP1J1CH

**Comment by yegor256** [comment] 2018-03-27 10:10
@vikasrachakonda it seems to be a duplicate of #348

**Closed by yegor256** 2018-03-27 10:10 UTC

**Comment by 0crat** [comment] 2018-03-27 10:31
The job is not in WBS, won't close the order
